// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: pkg/protocol/simulation.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SalesRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Region         string                 `protobuf:"bytes,1,opt,name=region,proto3" json:"region,omitempty"`
	Category       string                 `protobuf:"bytes,2,opt,name=category,proto3" json:"category,omitempty"`
	StartDate      string                 `protobuf:"bytes,3,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate        string                 `protobuf:"bytes,4,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	MinAmount      int64                  `protobuf:"varint,5,opt,name=min_amount,json=minAmount,proto3" json:"min_amount,omitempty"`
	MaxAmount      int64                  `protobuf:"varint,6,opt,name=max_amount,json=maxAmount,proto3" json:"max_amount,omitempty"`
	ProductKeyword string                 `protobuf:"bytes,7,opt,name=product_keyword,json=productKeyword,proto3" json:"product_keyword,omitempty"`
	BuyerKeyword   string                 `protobuf:"bytes,8,opt,name=buyer_keyword,json=buyerKeyword,proto3" json:"buyer_keyword,omitempty"`
	StartHour      *int32                 `protobuf:"varint,9,opt,name=start_hour,json=startHour,proto3,oneof" json:"start_hour,omitempty"`
	EndHour        *int32                 `protobuf:"varint,10,opt,name=end_hour,json=endHour,proto3,oneof" json:"end_hour,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SalesRequest) Reset() {
	*x = SalesRequest{}
	mi := &file_pkg_protocol_simulation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SalesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SalesRequest) ProtoMessage() {}

func (x *SalesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_simulation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SalesRequest.ProtoReflect.Descriptor instead.
func (*SalesRequest) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_simulation_proto_rawDescGZIP(), []int{0}
}

func (x *SalesRequest) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *SalesRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *SalesRequest) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *SalesRequest) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

func (x *SalesRequest) GetMinAmount() int64 {
	if x != nil {
		return x.MinAmount
	}
	return 0
}

func (x *SalesRequest) GetMaxAmount() int64 {
	if x != nil {
		return x.MaxAmount
	}
	return 0
}

func (x *SalesRequest) GetProductKeyword() string {
	if x != nil {
		return x.ProductKeyword
	}
	return ""
}

func (x *SalesRequest) GetBuyerKeyword() string {
	if x != nil {
		return x.BuyerKeyword
	}
	return ""
}

func (x *SalesRequest) GetStartHour() int32 {
	if x != nil && x.StartHour != nil {
		return *x.StartHour
	}
	return 0
}

func (x *SalesRequest) GetEndHour() int32 {
	if x != nil && x.EndHour != nil {
		return *x.EndHour
	}
	return 0
}

type SalesResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TotalSalesCount int64                  `protobuf:"varint,1,opt,name=total_sales_count,json=totalSalesCount,proto3" json:"total_sales_count,omitempty"`
	TotalRevenue    int64                  `protobuf:"varint,2,opt,name=total_revenue,json=totalRevenue,proto3" json:"total_revenue,omitempty"`
	AverageAmount   float64                `protobuf:"fixed64,3,opt,name=average_amount,json=averageAmount,proto3" json:"average_amount,omitempty"`
	RegionProcessed string                 `protobuf:"bytes,4,opt,name=region_processed,json=regionProcessed,proto3" json:"region_processed,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SalesResponse) Reset() {
	*x = SalesResponse{}
	mi := &file_pkg_protocol_simulation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SalesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SalesResponse) ProtoMessage() {}

func (x *SalesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_simulation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SalesResponse.ProtoReflect.Descriptor instead.
func (*SalesResponse) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_simulation_proto_rawDescGZIP(), []int{1}
}

func (x *SalesResponse) GetTotalSalesCount() int64 {
	if x != nil {
		return x.TotalSalesCount
	}
	return 0
}

func (x *SalesResponse) GetTotalRevenue() int64 {
	if x != nil {
		return x.TotalRevenue
	}
	return 0
}

func (x *SalesResponse) GetAverageAmount() float64 {
	if x != nil {
		return x.AverageAmount
	}
	return 0
}

func (x *SalesResponse) GetRegionProcessed() string {
	if x != nil {
		return x.RegionProcessed
	}
	return ""
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_pkg_protocol_simulation_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_simulation_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_simulation_proto_rawDescGZIP(), []int{2}
}

type SystemStats struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	CpuUsage         float64                `protobuf:"fixed64,1,opt,name=cpu_usage,json=cpuUsage,proto3" json:"cpu_usage,omitempty"`
	MemoryUsage      uint64                 `protobuf:"varint,2,opt,name=memory_usage,json=memoryUsage,proto3" json:"memory_usage,omitempty"`
	ActiveGoroutines uint32                 `protobuf:"varint,3,opt,name=active_goroutines,json=activeGoroutines,proto3" json:"active_goroutines,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SystemStats) Reset() {
	*x = SystemStats{}
	mi := &file_pkg_protocol_simulation_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemStats) ProtoMessage() {}

func (x *SystemStats) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_simulation_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemStats.ProtoReflect.Descriptor instead.
func (*SystemStats) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_simulation_proto_rawDescGZIP(), []int{3}
}

func (x *SystemStats) GetCpuUsage() float64 {
	if x != nil {
		return x.CpuUsage
	}
	return 0
}

func (x *SystemStats) GetMemoryUsage() uint64 {
	if x != nil {
		return x.MemoryUsage
	}
	return 0
}

func (x *SystemStats) GetActiveGoroutines() uint32 {
	if x != nil {
		return x.ActiveGoroutines
	}
	return 0
}

var File_pkg_protocol_simulation_proto protoreflect.FileDescriptor

const file_pkg_protocol_simulation_proto_rawDesc = "" +
	"\n" +
	"\x1dpkg/protocol/simulation.proto\x12\bprotocol\"\xe8\x02\n" +
	"\fSalesRequest\x12\x16\n" +
	"\x06region\x18\x01 \x01(\tR\x06region\x12\x1a\n" +
	"\bcategory\x18\x02 \x01(\tR\bcategory\x12\x1d\n" +
	"\n" +
	"start_date\x18\x03 \x01(\tR\tstartDate\x12\x19\n" +
	"\bend_date\x18\x04 \x01(\tR\aendDate\x12\x1d\n" +
	"\n" +
	"min_amount\x18\x05 \x01(\x03R\tminAmount\x12\x1d\n" +
	"\n" +
	"max_amount\x18\x06 \x01(\x03R\tmaxAmount\x12'\n" +
	"\x0fproduct_keyword\x18\a \x01(\tR\x0eproductKeyword\x12#\n" +
	"\rbuyer_keyword\x18\b \x01(\tR\fbuyerKeyword\x12\"\n" +
	"\n" +
	"start_hour\x18\t \x01(\x05H\x00R\tstartHour\x88\x01\x01\x12\x1e\n" +
	"\bend_hour\x18\n" +
	" \x01(\x05H\x01R\aendHour\x88\x01\x01B\r\n" +
	"\v_start_hourB\v\n" +
	"\t_end_hour\"\xb2\x01\n" +
	"\rSalesResponse\x12*\n" +
	"\x11total_sales_count\x18\x01 \x01(\x03R\x0ftotalSalesCount\x12#\n" +
	"\rtotal_revenue\x18\x02 \x01(\x03R\ftotalRevenue\x12%\n" +
	"\x0eaverage_amount\x18\x03 \x01(\x01R\raverageAmount\x12)\n" +
	"\x10region_processed\x18\x04 \x01(\tR\x0fregionProcessed\"\a\n" +
	"\x05Empty\"z\n" +
	"\vSystemStats\x12\x1b\n" +
	"\tcpu_usage\x18\x01 \x01(\x01R\bcpuUsage\x12!\n" +
	"\fmemory_usage\x18\x02 \x01(\x04R\vmemoryUsage\x12+\n" +
	"\x11active_goroutines\x18\x03 \x01(\rR\x10activeGoroutines2\x91\x01\n" +
	"\x11SimulationService\x12B\n" +
	"\x0fGetSalesMetrics\x12\x16.protocol.SalesRequest\x1a\x17.protocol.SalesResponse\x128\n" +
	"\x0eGetSystemStats\x12\x0f.protocol.Empty\x1a\x15.protocol.SystemStatsB\x19Z\x17simulation/pkg/protocolb\x06proto3"

var (
	file_pkg_protocol_simulation_proto_rawDescOnce sync.Once
	file_pkg_protocol_simulation_proto_rawDescData []byte
)

func file_pkg_protocol_simulation_proto_rawDescGZIP() []byte {
	file_pkg_protocol_simulation_proto_rawDescOnce.Do(func() {
		file_pkg_protocol_simulation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_protocol_simulation_proto_rawDesc), len(file_pkg_protocol_simulation_proto_rawDesc)))
	})
	return file_pkg_protocol_simulation_proto_rawDescData
}

var file_pkg_protocol_simulation_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_pkg_protocol_simulation_proto_goTypes = []any{
	(*SalesRequest)(nil),  // 0: protocol.SalesRequest
	(*SalesResponse)(nil), // 1: protocol.SalesResponse
	(*Empty)(nil),         // 2: protocol.Empty
	(*SystemStats)(nil),   // 3: protocol.SystemStats
}
var file_pkg_protocol_simulation_proto_depIdxs = []int32{
	0, // 0: protocol.SimulationService.GetSalesMetrics:input_type -> protocol.SalesRequest
	2, // 1: protocol.SimulationService.GetSystemStats:input_type -> protocol.Empty
	1, // 2: protocol.SimulationService.GetSalesMetrics:output_type -> protocol.SalesResponse
	3, // 3: protocol.SimulationService.GetSystemStats:output_type -> protocol.SystemStats
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_protocol_simulation_proto_init() }
func file_pkg_protocol_simulation_proto_init() {
	if File_pkg_protocol_simulation_proto != nil {
		return
	}
	file_pkg_protocol_simulation_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_protocol_simulation_proto_rawDesc), len(file_pkg_protocol_simulation_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_protocol_simulation_proto_goTypes,
		DependencyIndexes: file_pkg_protocol_simulation_proto_depIdxs,
		MessageInfos:      file_pkg_protocol_simulation_proto_msgTypes,
	}.Build()
	File_pkg_protocol_simulation_proto = out.File
	file_pkg_protocol_simulation_proto_goTypes = nil
	file_pkg_protocol_simulation_proto_depIdxs = nil
}
